// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/consts/consts.proto

package kiDB

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Operation int32

const (
	Operation_insert Operation = 0
	Operation_delete Operation = 1
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "insert",
		1: "delete",
	}
	Operation_value = map[string]int32{
		"insert": 0,
		"delete": 1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consts_consts_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_consts_consts_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_consts_consts_proto_rawDescGZIP(), []int{0}
}

type DataType int32

const (
	DataType_string   DataType = 0
	DataType_list     DataType = 1
	DataType_hash_map DataType = 2
	DataType_hash_set DataType = 3
	DataType_z_set    DataType = 4
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "string",
		1: "list",
		2: "hash_map",
		3: "hash_set",
		4: "z_set",
	}
	DataType_value = map[string]int32{
		"string":   0,
		"list":     1,
		"hash_map": 2,
		"hash_set": 3,
		"z_set":    4,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consts_consts_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_consts_consts_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_consts_consts_proto_rawDescGZIP(), []int{1}
}

var File_proto_consts_consts_proto protoreflect.FileDescriptor

var file_proto_consts_consts_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2f, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x69, 0x44,
	0x42, 0x2a, 0x23, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a,
	0x0a, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x10, 0x01, 0x2a, 0x47, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x6d, 0x61, 0x70, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x73,
	0x65, 0x74, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x7a, 0x5f, 0x73, 0x65, 0x74, 0x10, 0x04, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_consts_consts_proto_rawDescOnce sync.Once
	file_proto_consts_consts_proto_rawDescData = file_proto_consts_consts_proto_rawDesc
)

func file_proto_consts_consts_proto_rawDescGZIP() []byte {
	file_proto_consts_consts_proto_rawDescOnce.Do(func() {
		file_proto_consts_consts_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_consts_consts_proto_rawDescData)
	})
	return file_proto_consts_consts_proto_rawDescData
}

var file_proto_consts_consts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_consts_consts_proto_goTypes = []interface{}{
	(Operation)(0), // 0: kiDB.Operation
	(DataType)(0),  // 1: kiDB.DataType
}
var file_proto_consts_consts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_consts_consts_proto_init() }
func file_proto_consts_consts_proto_init() {
	if File_proto_consts_consts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_consts_consts_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_consts_consts_proto_goTypes,
		DependencyIndexes: file_proto_consts_consts_proto_depIdxs,
		EnumInfos:         file_proto_consts_consts_proto_enumTypes,
	}.Build()
	File_proto_consts_consts_proto = out.File
	file_proto_consts_consts_proto_rawDesc = nil
	file_proto_consts_consts_proto_goTypes = nil
	file_proto_consts_consts_proto_depIdxs = nil
}
